GET  https://keycloak.victoriasecret.md/realms/srWebTest/protocol/openid-connect/userinfo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI5NjI5Y2JjYy03ZTRlLTQwYjgtYjUwYS03OTQzYmJlOGI5MjcifQ.eyJleHAiOjE2OTM5NzQ0NjYsImlhdCI6MTY5MzkzODQ2NiwianRpIjoiMDhlNDNlN2UtZmFmNS00ZTRlLTk0NDgtMjdlMzYxOTYxZGQ3IiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay52aWN0b3JpYXNlY3JldC5tZC9yZWFsbXMvc3JXZWJUZXN0IiwiYXVkIjoiaHR0cHM6Ly9rZXljbG9hay52aWN0b3JpYXNlY3JldC5tZC9yZWFsbXMvc3JXZWJUZXN0Iiwic3ViIjoiOTRlOGIxZWItNGYzMi00Yzc2LTk4NDYtMDYwMmRlOWM5NTRiIiwidHlwIjoiUmVmcmVzaCIsImF6cCI6InRlc3QyIiwic2Vzc2lvbl9zdGF0ZSI6IjhjMGJiMTU1LTEwYmEtNDU1ZC05ZDY2LTJjMjdkYThkMzA1YiIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJzaWQiOiI4YzBiYjE1NS0xMGJhLTQ1NWQtOWQ2Ni0yYzI3ZGE4ZDMwNWIifQ.daqerHWu9cJA0egN_zM1V_FVRmWIHNopJkjLH52V9dc