server:
  port: 8081
  error:
    include-message: on_param


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/srweb
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true
  mail:
    from: support@victoriasecret.md
    copyTo: zakella@victoriasecret.md
    host: smtp.gmail.com
    port: 587
    username: ${SUPPORT_MAIL_USERNAME}
    password: ${SUPPORT_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com


  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_SERVER_URL}/realms/srWebTest/protocol/openid-connect/certs



keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  realm: master
  client-id: admin-cli
  admin-user: ${KEYCLOAK_ADMIN_USER}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}
  user-realm: srWebTest
  webclient-id: test2

frontend:
  reset-password-url: http://localhost:4200/reset-password

